### ISSUE TITLE
why would not you just make it auto download the WebDriver based on the browser and its version ! 

### ISSUE THREAD

**Issue by Alt0o** [maxamin/Linkedin-Easy-apply-Bot#1]
why would not you just make it auto download the WebDriver based on the browser and its version ! 
you could just make a simple line to make it auto detects the brwoser and its version, i can post it here if you want.
you can contact me on ```madmancanfly@gmail.com```

**Comment by maxamin** [comment]
Should be done,thanks for pointing that out
